project:
  type: website
  output-dir: _site
  pre-render: pre-render.R
  post-render: post-render.R

profile:
  default: student

website:
  title: "EDEP 625 Structural Equation Modeling"
  navbar:
    left:
      - href: syllabus.qmd
        text: Syllabus
      - href: lectures.qmd
        text: Lectures
      - href: labs.qmd
        text: R Labs
      - href: methods_walk_through.qmd
        text: Methods Walk Through
      - href: fin_proj.qmd
        text: Mini Projects
  

format:
  html:
    theme: darkly
    toc: true
    code-tools: true
