---
title: "Syllabus"
format:
  html:
    toc: true
  typst:
    margin:
      x: 1in
      y: 1in
---


::: {.content-visible when-format="html"}
[Download PDF](syllabus.pdf){.btn .btn-primary download="syllabus.pdf" role="button"}
:::

## Course Description

This course is an introductory course to structural equation modeling (SEM). Throughout the course, we will build on regression fundamentals to build models that capture more complicated relationships than standard regression and which can be applied to a wider variety of use cases. 

The core focus will be on path analysis, confirmatory factor analysis, and latent variable path analysis. As we approach each model, we will discuss how to specify, identify, fit, interpret, and report on the models we build. 

This is an applied class and will heavily involve discussions and labs. 

## Course Learning Objectives

By the end of this course, students will:

- Understand the kinds of research questions that can and cannot be answered by SEM models, 
- Build measured variable path analysis, confirmatory factor analysis and latent variable path analysis models with academic rigor, 
- Have a basic understanding of how MVPA, CFA, and LVPA can be extended (ex: longitudinal, multi-group),
- Build understanding of SEM research in their field and datasets available to answer questions.

## Program Objectives 

See the departmental [site](https://coe.hawaii.edu/edep/programs/gcert-ms/)

## Advanced Degree Learning Objectives

See the graduate division [site](https://manoa.hawaii.edu/graduate/advanced-degree-institutional-learning-objectives-ilo/)

## Required Materials

- No textbooks are required. Preparatory materials and slides will be linked in the course schedule.
- Laptop with internet connection
- R (free software) 
- Onyx (free software)

## Course Policies

### Attendance

This class is discussion- and lab-focused. In-person, on-time attendance & active participation are expected. Graded in-class work, labs, quizzes, discussion prompts, etc will be assigned during class and cannot be made up if the student is not present for any reason.  

### Assignments

Assignments are expected to be handed in on time. You are welcome to work with other students on homework, although you are expected to submit your own work with explanations in your own words.

#### Preparatory materials

These are readings or videos that introduce the topics we'll cover in class and should be completed prior to class. Graded in-class work may be based on these materials.

#### In-class assignments

Throughout the semester, students will complete a variety of activities in class for a grade. These are generally graded on a participation basis.

#### Labs

Most weeks part of the class time we will be labs, which are opportunities for students to apply what we discuss in class by building models.

#### Data search

You will need one or more large datasets from your field that you can use for mini projects. We will start to identify these early in the semester.

#### Mini projects 

Students will complete three mini projects on the three key models covered. This will be an extension of in-class labs we do and will rely on questions and data relevant to the student's field. These are not full research papers. Details will be forthcoming. Students will choose one of these to present to the class as a final presnetation. 

#### Methods Walk-through

Students will identify papers in their field that use one of the three key models discussed in the class and will present it to the class. 

#### Review

While not formally graded, students are expected to spend a few hours each week reviewing course materials, labs, and running their own analyses to solidify their understanding of SEM. Students are encouraged to form study groups.

## Grading

| Component | Weight |
|---|---|
| In-class work | [10%] |
| Labs | [10%] |
| Data search | [5%] |
| Methods Walk-through | [5%] |
| Final presentation | [10%] |
| Mini project 1 | [20%] |
| Mini project 2 | [20%] |
| Mini project 3 | [20%] |

| Score | Grade |
|---|---|
|A+|>= 97|
|A| 93-96|
|A-| 90-92|
|B+| 87-89 |
|B| 83-86|
|B-| 80-82|
|C+| 77-79|
|C| 73-76|
|C-| 70-72|
|D+| 67-69|
|D| 63-66|
|D-| 60-62|
|F| < 60|



# AI Fair Use

For the purposes of this course: to be added post-discussion. 

See https://docs.google.com/document/d/1cd0gKMM4fR4YDINjWfNT_-OBK4vAN4IUcdum1WErU3w/edit?usp=sharing.

# Academic integrity

Violations of academic integrity include, but are not limited to, cheating, fabrication, tampering, plagiarism, or facilitating such activities. Failure to meet this expectation will result in failure of the course and possible dismissal from the program. Plagiarism means using another's words, ideas, materials or work without properly acknowledging and documenting the source. Students are responsible for knowing the rules governing the use of another's work or materials and for acknowledging and documenting the source appropriately. Although I encourage collaboration with peers, all work that candidates ultimately submit in this course must be their own in their own words. If you are in doubt about whether your work is paraphrased or plagiarized, see the UH General and Graduate Information Catalog under [Student Regulations](https://manoa.hawaii.edu/studentsuccess/conduct-code/) and the UH Student Conduct Code for specific guidelines related to ethical behavior.

### Accommodations

If you have a disability and related access needs, please contact the [KOKUA program](https://www.hawaii.edu/kokua/) (UH Mānoa office for students with disabilities) at 956-7511, KOKUA@hawaii.edu, or go to Room 013 in the Queen Lili‘uokalani Center for Student Services. Please know that I will work with you and KOKUA to meet your access needs based on disability documentation.  

## Class Schedule

```{r}
#| echo: false
#| message: false
source("R/schedule.R")
knitr::kable(class_schedule_df)
```
