---
title: "Week 1: Introductions"
date: today
description: '<a href="lectures/w01_intros.pdf" download="w01_intros.pdf">Download PDF</a>'
format:
  revealjs:
    theme: simple
    slide-number: true
    embed-resources: true
---

## Agenda: 

1. Introductions
2. Syllabus
3. Acceptable AI use guide
6. R Intro & lab data 
5. Homework: Scavenger hunt: Finding datasets; review videos for variance, covariance, correlation. 

Notes: 
::: {.content-visible when-profile="teacher"}
- do a survey on R experience, qmd/rmd, lavaan (sem, cfa) packages, regression, prior SEM work. 


:::


## Introductions

About Me

- PhD Second Language Studies, UHM 
- Language Data Researcher & Language Data Scientist @ Amazon
- Data Scientist @ Amplify Education

::: {.content-visible when-profile="teacher"}
::: {.fragment}
Projects in machine learning, human-AI interface, and generative AI
:::
:::

## Introductions: Your turn!

- Name
- Department
- MA/PhD
- Research topics of interest
- Favorite animal

::: {.content-visible when-profile="teacher"}
::: {.notes}
ask students to introduce themselves
:::
:::

## Course Syllabus & Website

- Link to course site in Lamaku 
- Site: things for you to download (r labs, slide decks, data, syllabus, etc)
- Lamaku: Assignments, grades
- Syllabus
- Overview of other pages


## AI Use

Go to the [link](https://lamaku.hawaii.edu/d2l/lms/quizzing/admin/quizzes_manage.d2l?ou=206398&dst=1) & complete the survey on AI use. 

::: {.content-visible when-profile="teacher"}
::: {.notes}
First in-class assignment
:::
:::


## AI use: 

In pairs: Discuss your responses. Keep notes [here](https://docs.google.com/document/d/1cd0gKMM4fR4YDINjWfNT_-OBK4vAN4IUcdum1WErU3w/edit?usp=sharing).

- What are some positive or effective uses of AI? 
- What are some negative or ineffective uses of AI? 
- What's your response when people use AI for different activities (reports, assignments, etc)

## AI Use

Groups of 5: 

Review what's on the google Doc

What AI use guidelines would you propose for the class? 

## Data Intro

- Programme for International Student Assessment [PISA](https://www.oecd.org/en/about/programmes/pisa/pisa-test.html)
- International test 
- 15-year-olds’ ability to use reading, mathematics and science knowledge to meet real-life challenges
- 90 countries/economies
- Run every 3 years
- Includes assessment, surveys of students, parents, school leaders
- nationally representative sample

## Pisa Key Characteristics

- **Achievement scores are plausible values.** 
  - Each student sees a rotated subset of items; PISA uses a measurement model to draw a set of *plausible values* (`PV1`–`PV10`) representing where that student likely falls on the scale. 
  - In research, the correct way to handle this is to run each test 10x and average results across the test results. 
  - In practice, researchers sometimes take a single plausible value and treat it as the score or average across all 10 plausible values. 
  - In this class, for teaching purposes, we average across the 10 scores

## Data: Key Characteristics

- **Many variables are standardized** to be able to draw comparisons across diverse contexts. 
- We will work with [Pisa 2022](https://supreme-disco-rrvpg9q5qjp2p5w.github.dev/)
- files are large and so subsets of data are shared on the course site.


## R Lab 1

- EDA of the small subset
- Key question: 
- What strikes you as important in this data set? What - should we keep in mind as we model the data? 

::: {.content-visible when-profile="teacher"}
::: {.notes}
Self-assign into one of 3 groups: 

- Does not have R downloaded
- Has used < 1 semester
- Has used > 1 semester

:::
:::

## R setup (if needed)

Download R: https://cran.r-project.org/
Download R Studio (now Posit): https://docs.posit.co/ide/user/#rstudio-ide-oss-downloads

## Homework; 

1. Data scavenger hunt assignment
2. Prep videos for next week



